#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RUNS_ROOT="${RUNS_ROOT:-$REPO_ROOT/runs}"

TRAIN_JSONL="${TRAIN_JSONL:-${JSONL:-$RUNS_ROOT/mmlu_jsonl_gemma270m_s128/train.jsonl}}"
VALID_JSONL="${VALID_JSONL:-${JSONL_VALID:-$RUNS_ROOT/mmlu_jsonl_gemma270m_s128/valid.jsonl}}"
MODEL_DIR="${MODEL_DIR:-${PRETRAINED:-$SCRIPT_DIR/pretrained}}"
OUT_DIR="${OUT_DIR:-$RUNS_ROOT/gemma_3_270m_train}"
LOG_PATH="$OUT_DIR/train.log"
mkdir -p "$OUT_DIR"

ensure_mmlu_jsonl() {
  local path="$1"
  [ -z "$path" ] && return 0
  case "$path" in
    *mmlu_jsonl_*/*)  return 0 ;;
    *mmlu_jsonl_*)
      echo "[Error] Refusing deprecated mixed MMLU JSONL path: $path"
      echo "[Error] Use an official-split MMLU JSONL directory generated by run_prepare_data.sh."
      exit 1
      ;;
  esac
}

ensure_mmlu_jsonl "$TRAIN_JSONL"
ensure_mmlu_jsonl "$VALID_JSONL"

STEPS="${STEPS:-200}"
EPOCHS="${EPOCHS:-1}"
SEQ_LEN="${SEQ_LEN:-128}"
BATCH="${BATCH:-${BATCH_SIZE:-8}}"
GRAD_ACCUM="${GRAD_ACCUM:-${GRAD_ACCUM_STEPS:-1}}"
LR="${LR:-2e-4}"
WEIGHT_DECAY="${WEIGHT_DECAY:-0.0}"
LORA_R="${LORA_R:-${RANK:-8}}"
LORA_ALPHA="${LORA_ALPHA:-${ALPHA:-32}}"
LORA_DROPOUT="${LORA_DROPOUT:-0.0}"
LOGGING_STEPS="${LOGGING_STEPS:-${LOG_EVERY:-1}}"
WARMUP_STEPS="${WARMUP_STEPS:-0}"
WARMUP_RATIO="${WARMUP_RATIO:-}"
if [ -z "$WARMUP_RATIO" ] && [ "$WARMUP_STEPS" -gt 0 ] && [ "$STEPS" -gt 0 ]; then
  WARMUP_RATIO="$(awk -v w="$WARMUP_STEPS" -v t="$STEPS" 'BEGIN{ if (t <= 0) print 0; else printf "%.10f", w / t }')"
fi
WARMUP_RATIO="${WARMUP_RATIO:-0.0}"
MAX_GRAD_NORM="${MAX_GRAD_NORM:-1.0}"
TARGET_MODE="${TARGET_MODE:-full}"
SHUFFLE="${SHUFFLE:-0}"
SAVE_EVERY="${SAVE_EVERY:-0}"

LOCAL_BIN="$SCRIPT_DIR/build/train"

{
  echo "[Train] train_jsonl=$TRAIN_JSONL"
  echo "[Train] valid_jsonl=$VALID_JSONL"
  echo "[Train] model_dir=$MODEL_DIR"
  echo "[Train] out_dir=$OUT_DIR"
  echo "[Train] log_path=$LOG_PATH"

  if [ ! -x "$LOCAL_BIN" ]; then
    echo "[Build] Building local binary..."
    "$SCRIPT_DIR/build.sh"
  fi

  ARGS=(
    --model_dir "$MODEL_DIR"
    --jsonl_train "$TRAIN_JSONL"
    --jsonl_valid "$VALID_JSONL"
    --seq_len "$SEQ_LEN"
    --batch "$BATCH"
    --grad_accum "$GRAD_ACCUM"
    --lr "$LR"
    --warmup_ratio "$WARMUP_RATIO"
    --max_grad_norm "$MAX_GRAD_NORM"
    --weight_decay "$WEIGHT_DECAY"
    --targets "$TARGET_MODE"
    --lora_r "$LORA_R"
    --lora_alpha "$LORA_ALPHA"
    --lora_dropout "$LORA_DROPOUT"
    --logging_steps "$LOGGING_STEPS"
    --save_every "$SAVE_EVERY"
    --output_dir "$OUT_DIR"
  )

  if [ "$SHUFFLE" = "1" ]; then
    ARGS+=( --shuffle )
  else
    ARGS+=( --no_shuffle )
  fi

  if [ "$STEPS" -gt 0 ]; then
    ARGS+=( --max_steps "$STEPS" )
  else
    ARGS+=( --epochs "$EPOCHS" )
  fi

  "$LOCAL_BIN" "${ARGS[@]}"

  echo "[Train] Done. LoRA artifact directory: $OUT_DIR"
} 2>&1 | tee "$LOG_PATH"
